# Labeler configuration for automatic PR labeling
# See https://github.com/actions/labeler

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - '**/*.md'
      - '.github/ISSUE_TEMPLATE/**/*'
      - '.github/PULL_REQUEST_TEMPLATE.md'

python:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.py'
      - 'pyproject.toml'
      - 'requirements*.txt'

javascript:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.{js,ts,jsx,tsx}'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'tsconfig.json'

template:
  - changed-files:
    - any-glob-to-any-file:
      - 'template/**/*'
      - 'copier.yml'

ci-cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - '.github/dependabot.yml'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**/*'
      - '**/test_*.py'
      - '**/*_test.py'
      - '**/*.test.{js,ts}'
      - '**/*.spec.{js,ts}'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'pyproject.toml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'requirements*.txt'

security:
  - changed-files:
    - any-glob-to-any-file:
      - 'SECURITY.md'
      - '.github/workflows/security.yml'
      - '**/auth*.py'
      - '**/security*.py'

breaking-change:
  - body-contains:
    - 'BREAKING CHANGE'
    - 'BREAKING-CHANGE'

bug:
  - title-contains:
    - '[Bug]'
    - 'fix:'
    - 'Fix:'

enhancement:
  - title-contains:
    - '[Feature]'
    - 'feat:'
    - 'Feat:'
