# Hadolint configuration for Dockerfile linting
# https://github.com/hadolint/hadolint

failure-threshold: warning

ignored:
  - DL3008  # Pin versions in apt-get install (handled by base image)
  - DL3013  # Pin versions in pip (handled by requirements files)
  - DL3059  # Multiple consecutive RUN (optimized for layer caching)

trustedRegistries:
  - docker.io
  - ghcr.io
  - gcr.io

label-schema:
  author: error
  maintainer: error
  version: error
