import { QueryClient } from '@tanstack/react-query'
import { parse, stringify } from 'yaml'
import { formatRemovedAnswerKeyErrors } from './removedAnswerKeys'

export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 1000 * 60 * 5, // 5 minutes
      gcTime: 1000 * 60 * 30, // 30 minutes
      refetchOnWindowFocus: false,
      retry: 1,
    },
  },
})

const API_BASE_URL = import.meta.env.VITE_API_URL || '/api'

export interface Module {
  id: string
  name: string
  description: string
  category: 'core' | 'api' | 'docs' | 'infrastructure' | 'integration'
  dependencies: string[]
  conflicts: string[]
  tags: string[]
  version: string
  status: 'stable' | 'beta' | 'experimental'
}

export interface ValidationResult {
  valid: boolean
  errors: Array<{
    field: string
    message: string
  }>
  warnings: Array<{
    field: string
    message: string
  }>
}

export interface GenerateResult {
  success: boolean
  projectId: string
  downloadUrl: string
  message: string
}

/**
 * API client for Riso backend services.
 *
 * NOTE: getModules, validateConfig, generateProject, and downloadProject are
 * scaffolded for future backend integration. Currently only exportConfig and
 * importConfig are used for client-side YAML generation.
 */
export const api = {
  // Module catalog
  getModules: async (): Promise<Module[]> => {
    const response = await fetch(`${API_BASE_URL}/modules`)
    if (!response.ok) throw new Error('Failed to fetch modules')
    return response.json()
  },

  getModule: async (id: string): Promise<Module> => {
    const response = await fetch(`${API_BASE_URL}/modules/${id}`)
    if (!response.ok) throw new Error('Failed to fetch module')
    return response.json()
  },

  // Configuration validation
  validateConfig: async (config: Record<string, unknown>): Promise<ValidationResult> => {
    const response = await fetch(`${API_BASE_URL}/validate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(config),
    })
    if (!response.ok) throw new Error('Validation failed')
    return response.json()
  },

  // Project generation
  generateProject: async (config: Record<string, unknown>): Promise<GenerateResult> => {
    const response = await fetch(`${API_BASE_URL}/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(config),
    })
    if (!response.ok) throw new Error('Generation failed')
    return response.json()
  },

  // Download project
  downloadProject: async (projectId: string): Promise<Blob> => {
    const response = await fetch(`${API_BASE_URL}/download/${projectId}`)
    if (!response.ok) throw new Error('Download failed')
    return response.blob()
  },

  // Configuration management - using proper yaml library
  exportConfig: (config: Record<string, unknown>): string => {
    const header = `# Generated by Riso Web Interface\n# ${new Date().toISOString()}\n\n`
    return header + stringify(config)
  },

  importConfig: (yaml: string): Record<string, unknown> => {
    try {
      const parsed = parse(yaml)
      if (typeof parsed !== 'object' || parsed === null) {
        throw new Error('Invalid configuration format')
      }
      const config = parsed as Record<string, unknown>
      const removedKeyErrors = formatRemovedAnswerKeyErrors(config)
      if (removedKeyErrors.length > 0) {
        throw new Error(
          `Removed Copier answer keys are no longer supported:\n${removedKeyErrors.map((line) => `- ${line}`).join('\n')}`,
        )
      }
      return config
    } catch (error) {
      throw new Error(`Failed to parse YAML: ${error instanceof Error ? error.message : 'Unknown error'}`)
    }
  },
}
