import {
  Box,
  Server,
  Terminal,
  Cpu,
  FileCode,
  Database,
  Zap,
  Layers,
  Code,
  Rocket,
  Globe,
  Sparkles,
} from 'lucide-react'
import type { Preset, FileTreeNode } from './types'

// Reusable file tree patterns
const pythonCLITree: FileTreeNode[] = [
  {
    name: 'src/',
    type: 'folder',
    children: [
      { name: '__init__.py', type: 'file' },
      { name: 'cli.py', type: 'file', description: 'Typer CLI entry point' },
      { name: 'commands/', type: 'folder', children: [{ name: '*.py', type: 'file' }] },
    ],
  },
  { name: 'pyproject.toml', type: 'file', description: 'uv-managed dependencies' },
  { name: '.pre-commit-config.yaml', type: 'file' },
  { name: 'CLAUDE.md', type: 'file', description: 'AI assistant context' },
]

const pythonAPITree: FileTreeNode[] = [
  {
    name: 'src/',
    type: 'folder',
    children: [
      { name: 'api/', type: 'folder', children: [
        { name: 'main.py', type: 'file', description: 'FastAPI app' },
        { name: 'routes/', type: 'folder' },
        { name: 'models/', type: 'folder' },
      ]},
    ],
  },
  { name: 'tests/', type: 'folder' },
  { name: 'pyproject.toml', type: 'file' },
]

const fumadocsTree: FileTreeNode[] = [
  {
    name: 'docs/',
    type: 'folder',
    children: [
      { name: 'app/', type: 'folder', description: 'Next.js app router' },
      { name: 'content/', type: 'folder', description: 'MDX documentation' },
      { name: 'package.json', type: 'file' },
    ],
  },
]

const saasTree: FileTreeNode[] = [
  {
    name: 'apps/web/',
    type: 'folder',
    children: [
      { name: 'app/', type: 'folder', description: 'Next.js 16 app' },
      { name: 'components/', type: 'folder' },
      { name: 'lib/', type: 'folder', children: [
        { name: 'auth.ts', type: 'file', description: 'Clerk auth' },
        { name: 'db.ts', type: 'file', description: 'Prisma client' },
        { name: 'stripe.ts', type: 'file', description: 'Billing' },
      ]},
    ],
  },
  { name: 'packages/', type: 'folder', description: 'Shared code' },
  { name: 'prisma/schema.prisma', type: 'file' },
]

export const PRESETS: Preset[] = [
  {
    id: 'minimal-python',
    name: 'Python CLI Tool',
    description: 'Typer + Rich CLI with uv package management',
    purpose:
      'A minimal Python command-line application using Typer for argument parsing and Rich for beautiful terminal output. Perfect for building developer tools, automation scripts, or internal utilities.',
    useWhen: [
      'Building a command-line tool or script',
      'Need quick iteration without complex setup',
      'Want Python-native tooling with uv',
      'Creating internal team utilities',
    ],
    tags: ['python', 'cli', 'single-package', 'beginner'],
    complexity: 'beginner',
    techStack: ['Python 3.11+', 'Typer', 'Rich', 'uv', 'Ruff', 'pytest'],
    fileTree: pythonCLITree,
    estimatedFiles: 15,
    icon: <Box className="h-6 w-6" />,
    config: {
      project_layout: 'single-package',
      quality_profile: 'standard',
      cli_module: 'enabled',
      cli_languages: ['python'],
      api_module: 'disabled',
      docs_module: 'disabled',
      saas_infra_module: 'disabled',
      ai_tools_module: 'enabled',
    },
  },
  {
    id: 'python-api',
    name: 'Python REST API',
    description: 'FastAPI with auto-generated OpenAPI docs',
    purpose:
      'A production-ready FastAPI backend with automatic OpenAPI documentation integrated into Fumadocs. Includes structured logging, health checks, and strict type hints.',
    useWhen: [
      'Building a REST API backend',
      'Need auto-generated API documentation',
      'Want async Python with FastAPI',
      'Creating microservices or backend services',
    ],
    tags: ['python', 'api', 'backend', 'single-package', 'beginner'],
    complexity: 'beginner',
    techStack: ['FastAPI', 'Pydantic', 'uv', 'Fumadocs', 'OpenAPI'],
    fileTree: [...pythonAPITree, ...fumadocsTree],
    estimatedFiles: 35,
    icon: <Server className="h-6 w-6" />,
    config: {
      project_layout: 'single-package',
      quality_profile: 'standard',
      cli_module: 'disabled',
      api_module: 'enabled',
      api_languages: ['python'],
      api_features: 'none',
      docs_module: 'enabled',
      docs_framework: 'fumadocs',
      fumadocs_openapi: 'enabled',
      saas_infra_module: 'disabled',
      ai_tools_module: 'enabled',
    },
  },
  {
    id: 'rust-cli-python-api',
    name: 'Rust CLI + Python API',
    description: 'High-performance CLI paired with FastAPI backend',
    purpose:
      'Combines a blazing-fast Rust CLI (Clap + Tokio) with a Python FastAPI backend. The CLI can interact with the API or run standalone. Ideal for performance-critical tools that need a backend.',
    useWhen: [
      'Need a fast CLI that talks to a backend',
      'Building developer tools with remote features',
      'Want Rust performance + Python flexibility',
      'Creating hybrid local/cloud applications',
    ],
    tags: ['rust', 'python', 'cli', 'api', 'monorepo', 'intermediate'],
    complexity: 'intermediate',
    techStack: ['Rust', 'Clap', 'Tokio', 'FastAPI', 'Fumadocs'],
    fileTree: [
      {
        name: 'packages/',
        type: 'folder',
        children: [
          { name: 'cli/', type: 'folder', description: 'Rust CLI (Clap)' },
          { name: 'api/', type: 'folder', description: 'Python FastAPI' },
        ],
      },
      { name: 'Cargo.toml', type: 'file' },
      { name: 'pyproject.toml', type: 'file' },
      ...fumadocsTree,
    ],
    estimatedFiles: 50,
    icon: <Terminal className="h-6 w-6" />,
    config: {
      project_layout: 'monorepo',
      quality_profile: 'strict',
      cli_module: 'enabled',
      cli_languages: ['rust'],
      api_module: 'enabled',
      api_languages: ['python'],
      api_features: 'none',
      docs_module: 'enabled',
      docs_framework: 'fumadocs',
      saas_infra_module: 'disabled',
      ai_tools_module: 'enabled',
    },
  },
  {
    id: 'go-api',
    name: 'Go API + CLI',
    description: 'Gin REST API with Cobra CLI companion',
    purpose:
      'A high-performance Go backend using Gin for HTTP and Cobra for CLI. Includes structured logging, graceful shutdown, and Docker-ready configuration. Great for cloud-native services.',
    useWhen: [
      'Building high-throughput APIs',
      'Need Go for performance and concurrency',
      'Creating cloud-native microservices',
      'Want simple deployment (single binary)',
    ],
    tags: ['go', 'api', 'cli', 'backend', 'single-package', 'intermediate'],
    complexity: 'intermediate',
    techStack: ['Go 1.24', 'Gin', 'Cobra', 'Docker', 'Docusaurus'],
    fileTree: [
      {
        name: 'cmd/',
        type: 'folder',
        children: [
          { name: 'api/', type: 'folder', description: 'Gin server' },
          { name: 'cli/', type: 'folder', description: 'Cobra CLI' },
        ],
      },
      { name: 'internal/', type: 'folder', description: 'Business logic' },
      { name: 'go.mod', type: 'file' },
      { name: 'Dockerfile', type: 'file' },
    ],
    estimatedFiles: 30,
    icon: <Cpu className="h-6 w-6" />,
    config: {
      project_layout: 'single-package',
      quality_profile: 'strict',
      cli_module: 'enabled',
      cli_languages: ['go'],
      api_module: 'enabled',
      api_languages: ['go'],
      api_features: 'none',
      docs_module: 'enabled',
      docs_framework: 'docusaurus',
      saas_infra_module: 'disabled',
      ai_tools_module: 'enabled',
    },
  },
  {
    id: 'typescript-mcp',
    name: 'TypeScript MCP Server',
    description: 'Model Context Protocol server for AI tools',
    purpose:
      'An MCP (Model Context Protocol) server in TypeScript that integrates with Claude, Cursor, and other AI assistants. Includes example tools, resources, and prompts. Perfect for extending AI capabilities.',
    useWhen: [
      'Building AI assistant integrations',
      'Creating tools for Claude or Cursor',
      'Want to extend AI with custom capabilities',
      'Building AI-powered developer tools',
    ],
    tags: ['node', 'mcp', 'ai-ml', 'single-package', 'intermediate'],
    complexity: 'intermediate',
    techStack: ['TypeScript', '@modelcontextprotocol/sdk', 'Fumadocs'],
    fileTree: [
      {
        name: 'src/',
        type: 'folder',
        children: [
          { name: 'index.ts', type: 'file', description: 'MCP server entry' },
          { name: 'tools/', type: 'folder', description: 'Custom tools' },
          { name: 'resources/', type: 'folder', description: 'Data resources' },
          { name: 'prompts/', type: 'folder', description: 'Prompt templates' },
        ],
      },
      { name: 'package.json', type: 'file' },
      { name: 'tsconfig.json', type: 'file' },
    ],
    estimatedFiles: 25,
    icon: <FileCode className="h-6 w-6" />,
    config: {
      project_layout: 'single-package',
      quality_profile: 'standard',
      cli_module: 'disabled',
      api_module: 'disabled',
      mcp_module: 'enabled',
      mcp_languages: ['typescript'],
      docs_module: 'enabled',
      docs_framework: 'fumadocs',
      saas_infra_module: 'disabled',
      ai_tools_module: 'enabled',
    },
  },
  {
    id: 'graphql-api',
    name: 'GraphQL API',
    description: 'Strawberry GraphQL with subscriptions',
    purpose:
      'A Python GraphQL API using Strawberry with real-time subscriptions via WebSockets. Includes GraphiQL playground and type-safe resolvers. Great for complex data requirements.',
    useWhen: [
      'Building APIs with complex data relationships',
      'Need real-time updates via subscriptions',
      'Want type-safe GraphQL with Python',
      'Creating data-intensive applications',
    ],
    tags: ['python', 'api', 'backend', 'single-package', 'intermediate'],
    complexity: 'intermediate',
    techStack: ['Strawberry GraphQL', 'FastAPI', 'WebSockets', 'Fumadocs'],
    fileTree: [
      {
        name: 'src/',
        type: 'folder',
        children: [
          { name: 'schema/', type: 'folder', description: 'GraphQL types' },
          { name: 'resolvers/', type: 'folder' },
          { name: 'subscriptions/', type: 'folder' },
        ],
      },
      ...fumadocsTree,
    ],
    estimatedFiles: 40,
    icon: <Database className="h-6 w-6" />,
    config: {
      project_layout: 'single-package',
      quality_profile: 'strict',
      cli_module: 'disabled',
      api_module: 'enabled',
      api_languages: ['python'],
      api_features: 'graphql,websocket',
      docs_module: 'enabled',
      docs_framework: 'fumadocs',
      fumadocs_openapi: 'enabled',
      saas_infra_module: 'disabled',
      ai_tools_module: 'enabled',
    },
  },
  {
    id: 'fullstack',
    name: 'Full-Stack Monorepo',
    description: 'Python API + MCP + Fumadocs in one repo',
    purpose:
      'A complete full-stack setup with FastAPI backend, Python MCP server for AI integration, and Fumadocs for documentation. Uses monorepo structure with shared code packages.',
    useWhen: [
      'Building a complete product with multiple components',
      'Need API, AI tools, and docs in one place',
      'Want shared code between services',
      'Creating a developer platform or tool',
    ],
    tags: ['python', 'api', 'mcp', 'docs', 'monorepo', 'fullstack', 'advanced'],
    complexity: 'advanced',
    techStack: ['FastAPI', 'Strawberry', 'MCP', 'Fumadocs', 'WebSockets'],
    fileTree: [
      {
        name: 'packages/',
        type: 'folder',
        children: [
          { name: 'api/', type: 'folder', description: 'FastAPI + GraphQL' },
          { name: 'mcp/', type: 'folder', description: 'MCP server' },
          { name: 'shared/', type: 'folder', description: 'Shared logic' },
        ],
      },
      ...fumadocsTree,
      { name: 'pyproject.toml', type: 'file', description: 'Workspace root' },
    ],
    estimatedFiles: 75,
    icon: <Zap className="h-6 w-6" />,
    config: {
      project_layout: 'monorepo',
      quality_profile: 'strict',
      cli_module: 'enabled',
      cli_languages: ['python'],
      api_module: 'enabled',
      api_languages: ['python'],
      api_features: 'graphql,websocket',
      mcp_module: 'enabled',
      mcp_languages: ['python'],
      shared_logic: 'enabled',
      docs_module: 'enabled',
      docs_framework: 'fumadocs',
      fumadocs_openapi: 'enabled',
      fumadocs_llms_txt: 'enabled',
      saas_infra_module: 'disabled',
      ai_tools_module: 'enabled',
    },
  },
  {
    id: 'polyglot-monorepo',
    name: 'Polyglot Monorepo',
    description: 'Mix Rust, Go, and TypeScript in one repo',
    purpose:
      'A polyglot monorepo combining Rust CLI for performance, Go API for concurrency, and TypeScript MCP for AI integration. Each component uses its ideal language.',
    useWhen: [
      'Want best language for each component',
      'Building complex systems with varied requirements',
      'Need Rust speed + Go concurrency + TS flexibility',
      'Creating enterprise-grade tooling',
    ],
    tags: ['rust', 'go', 'node', 'cli', 'api', 'mcp', 'monorepo', 'advanced'],
    complexity: 'advanced',
    techStack: ['Rust', 'Go', 'TypeScript', 'Clap', 'Gin', 'MCP SDK'],
    fileTree: [
      {
        name: 'packages/',
        type: 'folder',
        children: [
          { name: 'cli/', type: 'folder', description: 'Rust CLI' },
          { name: 'api/', type: 'folder', description: 'Go API' },
          { name: 'mcp/', type: 'folder', description: 'TS MCP server' },
          { name: 'shared/', type: 'folder' },
        ],
      },
      { name: 'Cargo.toml', type: 'file' },
      { name: 'go.work', type: 'file' },
      { name: 'package.json', type: 'file' },
    ],
    estimatedFiles: 80,
    icon: <Layers className="h-6 w-6" />,
    config: {
      project_layout: 'monorepo',
      quality_profile: 'strict',
      cli_module: 'enabled',
      cli_languages: ['rust'],
      api_module: 'enabled',
      api_languages: ['go'],
      mcp_module: 'enabled',
      mcp_languages: ['typescript'],
      shared_logic: 'enabled',
      docs_module: 'enabled',
      docs_framework: 'fumadocs',
      saas_infra_module: 'disabled',
      ai_tools_module: 'enabled',
    },
  },
  {
    id: 'ml-ai-project',
    name: 'ML/AI Project',
    description: 'Python API + MCP for AI/ML workflows',
    purpose:
      'Optimized for machine learning projects with FastAPI for serving models, MCP for AI assistant integration, and Sphinx docs for research documentation.',
    useWhen: [
      'Building ML model serving infrastructure',
      'Creating AI-powered applications',
      'Need real-time inference via WebSockets',
      'Want AI assistant integration for research',
    ],
    tags: ['python', 'api', 'mcp', 'ai-ml', 'monorepo', 'intermediate'],
    complexity: 'intermediate',
    techStack: ['FastAPI', 'MCP', 'WebSockets', 'Sphinx Shibuya'],
    fileTree: [
      {
        name: 'packages/',
        type: 'folder',
        children: [
          { name: 'api/', type: 'folder', description: 'Model serving API' },
          { name: 'mcp/', type: 'folder', description: 'AI tool integration' },
          { name: 'cli/', type: 'folder', description: 'Training CLI' },
        ],
      },
      {
        name: 'docs/',
        type: 'folder',
        description: 'Sphinx documentation',
      },
    ],
    estimatedFiles: 55,
    icon: <Code className="h-6 w-6" />,
    config: {
      project_layout: 'monorepo',
      quality_profile: 'standard',
      cli_module: 'enabled',
      cli_languages: ['python'],
      api_module: 'enabled',
      api_languages: ['python'],
      api_features: 'websocket',
      mcp_module: 'enabled',
      mcp_languages: ['python'],
      docs_module: 'enabled',
      docs_framework: 'sphinx-shibuya',
      saas_infra_module: 'disabled',
      ai_tools_module: 'enabled',
    },
  },
  {
    id: 'saas-starter',
    name: 'SaaS Starter',
    description: 'Next.js 16 + Clerk + Stripe + Neon',
    purpose:
      'A complete SaaS foundation with Next.js 16, Clerk authentication, Stripe billing, Neon Postgres, and Prisma ORM. Includes auth flows, subscription management, and analytics.',
    useWhen: [
      'Launching a SaaS product',
      'Need auth + billing out of the box',
      'Want Vercel-optimized deployment',
      'Building B2C or B2B applications',
    ],
    tags: ['node', 'saas', 'fullstack', 'monorepo', 'advanced'],
    complexity: 'advanced',
    techStack: ['Next.js 16', 'Clerk', 'Stripe', 'Neon', 'Prisma', 'PostHog'],
    fileTree: saasTree,
    estimatedFiles: 100,
    icon: <Rocket className="h-6 w-6" />,
    config: {
      project_layout: 'monorepo',
      quality_profile: 'strict',
      api_module: 'enabled',
      api_languages: ['node'],
      docs_module: 'enabled',
      docs_framework: 'fumadocs',
      saas_infra_module: 'enabled',
      saas_runtime: 'nextjs-16',
      saas_hosting: 'vercel',
      saas_database: 'neon',
      saas_orm: 'prisma',
      saas_auth_module: 'enabled',
      saas_auth_provider: 'clerk',
      saas_billing_module: 'enabled',
      saas_billing_provider: 'stripe',
      saas_app_module: 'enabled',
      saas_analytics: 'posthog',
      ai_tools_module: 'enabled',
    },
  },
  {
    id: 'microservices',
    name: 'Microservices Monorepo',
    description: 'Multiple APIs with shared Docusaurus docs',
    purpose:
      'A microservices architecture with Python API using GraphQL, shared logic packages, and comprehensive Docusaurus documentation with OpenAPI integration.',
    useWhen: [
      'Building distributed systems',
      'Need multiple services in one repo',
      'Want GraphQL API with documentation',
      'Creating platform with multiple APIs',
    ],
    tags: ['python', 'api', 'docs', 'monorepo', 'backend', 'intermediate'],
    complexity: 'intermediate',
    techStack: ['FastAPI', 'GraphQL', 'Docusaurus', 'OpenAPI', 'Mermaid'],
    fileTree: [
      {
        name: 'services/',
        type: 'folder',
        children: [
          { name: 'users/', type: 'folder' },
          { name: 'orders/', type: 'folder' },
          { name: 'shared/', type: 'folder' },
        ],
      },
      {
        name: 'docs/',
        type: 'folder',
        description: 'Docusaurus site',
      },
    ],
    estimatedFiles: 60,
    icon: <Globe className="h-6 w-6" />,
    config: {
      project_layout: 'monorepo',
      quality_profile: 'strict',
      cli_module: 'enabled',
      cli_languages: ['python'],
      api_module: 'enabled',
      api_languages: ['python'],
      api_features: 'graphql',
      shared_logic: 'enabled',
      docs_module: 'enabled',
      docs_framework: 'docusaurus',
      docusaurus_openapi: 'enabled',
      docusaurus_mermaid: 'enabled',
      saas_infra_module: 'disabled',
      ai_tools_module: 'enabled',
    },
  },
  {
    id: 'docs-only',
    name: 'Documentation Site',
    description: 'Standalone Docusaurus with blog + search',
    purpose:
      'A feature-rich documentation site using Docusaurus with blog, Mermaid diagrams, local search, and AI-friendly llms.txt generation. Perfect for open-source projects or product docs.',
    useWhen: [
      'Creating project documentation',
      'Need a blog alongside docs',
      'Want diagrams and rich content',
      'Building open-source project site',
    ],
    tags: ['docs', 'single-package', 'beginner'],
    complexity: 'beginner',
    techStack: ['Docusaurus', 'MDX', 'Mermaid', 'llms.txt'],
    fileTree: [
      {
        name: 'docs/',
        type: 'folder',
        children: [
          { name: 'intro.md', type: 'file' },
          { name: 'guides/', type: 'folder' },
          { name: 'api/', type: 'folder' },
        ],
      },
      { name: 'blog/', type: 'folder' },
      { name: 'docusaurus.config.js', type: 'file' },
      { name: 'package.json', type: 'file' },
    ],
    estimatedFiles: 20,
    icon: <Sparkles className="h-6 w-6" />,
    config: {
      project_layout: 'single-package',
      quality_profile: 'standard',
      cli_module: 'disabled',
      api_module: 'disabled',
      docs_module: 'enabled',
      docs_framework: 'docusaurus',
      docusaurus_faster: 'enabled',
      docusaurus_blog: 'enabled',
      docusaurus_mermaid: 'enabled',
      docusaurus_llms_txt: 'enabled',
      saas_infra_module: 'disabled',
      ai_tools_module: 'disabled',
    },
  },
  {
    id: 'enterprise-saas',
    name: 'Enterprise SaaS',
    description: 'SaaS with WorkOS SSO + changelog + security',
    purpose:
      'Enterprise-grade SaaS with WorkOS for SSO/SCIM, Stripe billing, changelog management, and comprehensive security features. Built for B2B with team management.',
    useWhen: [
      'Building enterprise B2B SaaS',
      'Need SSO and team management',
      'Want audit logs and compliance',
      'Creating multi-tenant applications',
    ],
    tags: ['node', 'saas', 'fullstack', 'monorepo', 'advanced'],
    complexity: 'advanced',
    techStack: ['Next.js 16', 'Clerk', 'WorkOS', 'Stripe', 'Neon', 'PostHog'],
    fileTree: [
      ...saasTree,
      {
        name: 'packages/changelog/',
        type: 'folder',
        description: 'Changelog management',
      },
    ],
    estimatedFiles: 120,
    icon: <Rocket className="h-6 w-6" />,
    config: {
      project_layout: 'monorepo',
      quality_profile: 'strict',
      api_module: 'enabled',
      api_languages: ['node'],
      docs_module: 'enabled',
      docs_framework: 'fumadocs',
      saas_infra_module: 'enabled',
      saas_runtime: 'nextjs-16',
      saas_hosting: 'vercel',
      saas_database: 'neon',
      saas_orm: 'prisma',
      saas_auth_module: 'enabled',
      saas_auth_provider: 'clerk',
      saas_billing_module: 'enabled',
      saas_billing_provider: 'stripe',
      saas_app_module: 'enabled',
      saas_analytics: 'posthog',
      changelog_module: 'enabled',
      ai_tools_module: 'enabled',
    },
  },
]
