---
name: Feature Request
description: Suggest a new feature or enhancement for Riso
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the sections below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        Is your feature request related to a problem? Please describe.
        A clear description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        Describe the solution you'd like.
        A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: |
        Describe alternatives you've considered.
        A clear description of any alternative solutions or features you've considered.
      placeholder: |
        - Alternative 1: ...
        - Alternative 2: ...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      multiple: true
      options:
        - Template system
        - CLI module
        - API module (Python/FastAPI)
        - API module (Node/Fastify)
        - GraphQL module
        - MCP module
        - WebSocket module
        - Documentation site
        - SaaS starter
        - Quality tools
        - CI/CD workflows
        - Hooks (pre/post generation)
        - New module type
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Significant impact
        - Medium - Moderate impact
        - Low - Nice to have
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: |
        Describe specific use cases where this feature would be helpful.
        Help us understand how you would use this feature in practice.
      placeholder: |
        1. When building a new project with X, I would...
        2. This would help with Y by...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: |
        If you have ideas about how this could be implemented, please share them.
        This is optional but can help speed up implementation.
      placeholder: |
        This could be implemented by...
        - Adding a new prompt in copier.yml
        - Creating new template files in...
        - Updating the hooks to...

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: |
        If there are examples of this feature in other projects or tools, please share them.
        Links, screenshots, or code snippets are helpful.
      placeholder: |
        Similar to how [project] does it: https://...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to implementing this feature?
      options:
        - label: I would be willing to submit a pull request for this feature
          required: false
        - label: I would be willing to help test this feature
          required: false
        - label: I would be willing to help with documentation
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and pull requests to ensure this hasn't been requested
          required: true
        - label: I have provided a clear description of the feature and its benefits
          required: true
        - label: This feature aligns with Riso's goals as a modular template system
          required: true
