---
name: Question
description: Ask a question about using Riso
title: "[Question]: "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please check the documentation first:
        - [README](https://github.com/wyattowalsh/riso/blob/main/README.md)
        - [AGENTS.md](https://github.com/wyattowalsh/riso/blob/main/AGENTS.md)
        - [Documentation](https://github.com/wyattowalsh/riso/tree/main/docs)

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What is your question about?
      options:
        - Getting started
        - Template rendering
        - CLI module
        - API modules (FastAPI/Fastify)
        - GraphQL module
        - MCP module
        - Documentation sites
        - SaaS starter
        - Quality tools and testing
        - CI/CD workflows
        - Customizing templates
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Please provide context that might help us answer your question.
        What are you trying to accomplish? What have you tried so far?
      placeholder: |
        I'm trying to...
        I've looked at...
        I'm not sure how to...

  - type: textarea
    id: attempted
    attributes:
      label: What I've Tried
      description: |
        Have you tried anything already? What happened?
      placeholder: |
        I tried...
        The result was...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true
