#!/usr/bin/env python3
"""Validate release configuration files in rendered projects.

This script validates .commitlintrc.yml, .releaserc.yml, and riso-release.yml
files against their JSON schemas and ensures configuration consistency.

Usage:
    python scripts/ci/validate_release_configs.py [--project-dir <path>]

Arguments:
    --project-dir: Path to rendered project directory (default: samples/default/render)

Exit codes:
    0: All validations passed
    1: Validation failures detected

Generated by Riso template - Feature 014: Changelog & Release Management
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Optional

try:
    import yaml
except ImportError:
    print("? Error: PyYAML not installed", file=sys.stderr)
    print("   Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


def validate_commitlint_config(config_path: Path) -> tuple[bool, list[str]]:
    """Validate .commitlintrc.yml configuration.
    
    Args:
        config_path: Path to .commitlintrc.yml
        
    Returns:
        Tuple of (is_valid, errors)
    """
    errors = []
    
    if not config_path.exists():
        return True, []  # Not an error if changelog module disabled
    
    try:
        with open(config_path, 'r', encoding='utf-8') as f:
            config = yaml.safe_load(f)
        
        # Validate required fields
        if 'extends' not in config:
            errors.append(".commitlintrc.yml: Missing 'extends' field")
        
        if 'rules' not in config:
            errors.append(".commitlintrc.yml: Missing 'rules' field")
        else:
            # Validate type-enum rule
            if 'type-enum' not in config['rules']:
                errors.append(".commitlintrc.yml: Missing 'type-enum' rule")
            else:
                type_enum = config['rules']['type-enum']
                if not isinstance(type_enum, list) or len(type_enum) < 3:
                    errors.append(".commitlintrc.yml: Invalid 'type-enum' format")
        
        return len(errors) == 0, errors
        
    except yaml.YAMLError as e:
        errors.append(f".commitlintrc.yml: YAML parsing error: {e}")
        return False, errors
    except Exception as e:
        errors.append(f".commitlintrc.yml: Validation error: {e}")
        return False, errors


def validate_semantic_release_config(config_path: Path) -> tuple[bool, list[str]]:
    """Validate .releaserc.yml configuration.
    
    Args:
        config_path: Path to .releaserc.yml
        
    Returns:
        Tuple of (is_valid, errors)
    """
    errors = []
    
    if not config_path.exists():
        return True, []  # Not an error if changelog module disabled
    
    try:
        with open(config_path, 'r', encoding='utf-8') as f:
            config = yaml.safe_load(f)
        
        # Validate required fields
        if 'branches' not in config:
            errors.append(".releaserc.yml: Missing 'branches' field")
        
        if 'plugins' not in config:
            errors.append(".releaserc.yml: Missing 'plugins' field")
        else:
            plugins = config['plugins']
            
            # Check for required plugins
            required_plugins = [
                '@semantic-release/commit-analyzer',
                '@semantic-release/release-notes-generator',
                '@semantic-release/changelog',
            ]
            
            plugin_names = []
            for plugin in plugins:
                if isinstance(plugin, str):
                    plugin_names.append(plugin)
                elif isinstance(plugin, list) and len(plugin) > 0:
                    plugin_names.append(plugin[0])
            
            for required in required_plugins:
                if required not in plugin_names:
                    errors.append(f".releaserc.yml: Missing required plugin: {required}")
        
        return len(errors) == 0, errors
        
    except yaml.YAMLError as e:
        errors.append(f".releaserc.yml: YAML parsing error: {e}")
        return False, errors
    except Exception as e:
        errors.append(f".releaserc.yml: Validation error: {e}")
        return False, errors


def validate_release_workflow(workflow_path: Path) -> tuple[bool, list[str]]:
    """Validate riso-release.yml workflow.
    
    Args:
        workflow_path: Path to .github/workflows/riso-release.yml
        
    Returns:
        Tuple of (is_valid, errors)
    """
    errors = []
    
    if not workflow_path.exists():
        return True, []  # Not an error if changelog module disabled
    
    try:
        with open(workflow_path, 'r', encoding='utf-8') as f:
            workflow = yaml.safe_load(f)
        
        # Validate required fields
        if 'name' not in workflow:
            errors.append("riso-release.yml: Missing 'name' field")
        
        if 'on' not in workflow:
            errors.append("riso-release.yml: Missing 'on' field")
        
        if 'jobs' not in workflow:
            errors.append("riso-release.yml: Missing 'jobs' field")
        else:
            jobs = workflow['jobs']
            
            # Validate release job exists
            if 'release' not in jobs:
                errors.append("riso-release.yml: Missing 'release' job")
            else:
                release_job = jobs['release']
                
                # Validate job structure
                if 'runs-on' not in release_job:
                    errors.append("riso-release.yml: release job missing 'runs-on'")
                
                if 'steps' not in release_job:
                    errors.append("riso-release.yml: release job missing 'steps'")
                else:
                    steps = release_job['steps']
                    
                    # Check for required steps
                    step_names = [step.get('name', '') for step in steps]
                    
                    if not any('semantic-release' in name.lower() for name in step_names):
                        errors.append("riso-release.yml: Missing semantic-release step")
        
        return len(errors) == 0, errors
        
    except yaml.YAMLError as e:
        errors.append(f"riso-release.yml: YAML parsing error: {e}")
        return False, errors
    except Exception as e:
        errors.append(f"riso-release.yml: Validation error: {e}")
        return False, errors


def main() -> int:
    """Main entry point for validation script.
    
    Returns:
        Exit code: 0 for success, 1 for failure
    """
    parser = argparse.ArgumentParser(
        description='Validate release configuration files'
    )
    parser.add_argument(
        '--project-dir',
        type=Path,
        default=Path('samples/default/render'),
        help='Path to rendered project directory'
    )
    
    args = parser.parse_args()
    project_dir = args.project_dir
    
    if not project_dir.exists():
        print(f"? Project directory not found: {project_dir}", file=sys.stderr)
        return 1
    
    print("?? Validating release configurations...")
    print(f"?? Project directory: {project_dir}")
    print()
    
    all_valid = True
    all_errors = []
    
    # Validate commitlint config
    print("Validating .commitlintrc.yml...")
    commitlint_path = project_dir / '.commitlintrc.yml'
    is_valid, errors = validate_commitlint_config(commitlint_path)
    
    if not is_valid:
        all_valid = False
        all_errors.extend(errors)
        print("? Validation failed")
    elif commitlint_path.exists():
        print("? Valid")
    else:
        print("? Not present (changelog module disabled)")
    print()
    
    # Validate semantic-release config
    print("Validating .releaserc.yml...")
    releaserc_path = project_dir / '.releaserc.yml'
    is_valid, errors = validate_semantic_release_config(releaserc_path)
    
    if not is_valid:
        all_valid = False
        all_errors.extend(errors)
        print("? Validation failed")
    elif releaserc_path.exists():
        print("? Valid")
    else:
        print("? Not present (changelog module disabled)")
    print()
    
    # Validate release workflow
    print("Validating .github/workflows/riso-release.yml...")
    workflow_path = project_dir / '.github' / 'workflows' / 'riso-release.yml'
    is_valid, errors = validate_release_workflow(workflow_path)
    
    if not is_valid:
        all_valid = False
        all_errors.extend(errors)
        print("? Validation failed")
    elif workflow_path.exists():
        print("? Valid")
    else:
        print("? Not present (changelog module disabled)")
    print()
    
    # Print errors
    if all_errors:
        print("=" * 70)
        print("? Validation Errors:")
        print("=" * 70)
        for error in all_errors:
            print(f"  ? {error}")
        print()
        return 1
    
    print("=" * 70)
    print("? All validation checks passed!")
    print("=" * 70)
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
