#!/usr/bin/env python3
"""
Validate documentation configurations generated by Riso template.
Feature: 018-docs-sites-overhaul

Usage:
    python scripts/ci/validate_docs_config.py [path_to_rendered_project]
"""

import json
import sys
from pathlib import Path
from typing import Dict, List, Optional


class DocsConfigValidator:
    """Validate documentation configuration completeness and correctness."""

    def __init__(self, project_root: Path):
        self.project_root = project_root
        self.errors: List[str] = []
        self.warnings: List[str] = []

    def validate(self) -> bool:
        """
        Run all validation checks.
        
        Returns:
            True if validation passed, False if critical errors found
        """
        # Load copier answers to understand configuration
        answers = self._load_copier_answers()
        if not answers:
            self.errors.append("Could not load .copier-answers.yml")
            return False

        docs_site = answers.get("docs_site", "none")
        
        if docs_site == "none":
            print("✅ No documentation configured (docs_site=none)")
            return True

        # Validate based on framework
        if docs_site == "sphinx-shibuya":
            self._validate_sphinx(answers)
        elif docs_site == "fumadocs":
            self._validate_fumadocs(answers)
        elif docs_site == "docusaurus":
            self._validate_docusaurus(answers)
        else:
            self.errors.append(f"Unknown docs_site value: {docs_site}")

        # Report results
        if self.warnings:
            print("\n⚠️  Warnings:")
            for warning in self.warnings:
                print(f"  - {warning}")

        if self.errors:
            print("\n❌ Errors:")
            for error in self.errors:
                print(f"  - {error}")
            return False

        print(f"\n✅ {docs_site} configuration valid")
        return True

    def _load_copier_answers(self) -> Optional[Dict]:
        """Load and parse .copier-answers.yml."""
        answers_file = self.project_root / ".copier-answers.yml"
        if not answers_file.exists():
            return None

        answers = {}
        for line in answers_file.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if ":" not in line:
                continue
            key, value = line.split(":", 1)
            answers[key.strip()] = value.strip()
        return answers

    def _validate_sphinx(self, answers: Dict) -> None:
        """Validate Sphinx-specific configuration."""
        # Check for required files
        required_files = [
            "docs/conf.py",
            "docs/index.rst",
            "Makefile.docs",
        ]
        
        for file_path in required_files:
            full_path = self.project_root / file_path
            if not full_path.exists():
                self.errors.append(f"Missing required Sphinx file: {file_path}")

        # Check conf.py contains required configuration
        conf_py = self.project_root / "docs" / "conf.py"
        if conf_py.exists():
            content = conf_py.read_text()
            
            # Check for autodoc extension
            if "sphinx.ext.autodoc" not in content:
                self.warnings.append("sphinx.ext.autodoc extension not found in conf.py")
            
            # Check for theme configuration
            if "shibuya" not in content:
                self.warnings.append("Shibuya theme not configured in conf.py")
            
            # Check for sys.path modification
            if "sys.path.insert" not in content:
                self.errors.append("sys.path modification not found in conf.py (required for autodoc)")

        # Check Makefile.docs
        makefile = self.project_root / "Makefile.docs"
        if makefile.exists():
            content = makefile.read_text()
            required_targets = ["docs", "linkcheck", "clean-docs"]
            for target in required_targets:
                if f"{target}:" not in content and f".PHONY: {target}" not in content:
                    self.errors.append(f"Missing Makefile target: {target}")

    def _validate_fumadocs(self, answers: Dict) -> None:
        """Validate Fumadocs-specific configuration."""
        # Check for required files
        required_files = [
            "apps/docs-fumadocs/next.config.mjs",
            "apps/docs-fumadocs/app/layout.tsx",
        ]
        
        for file_path in required_files:
            full_path = self.project_root / file_path
            if not full_path.exists():
                self.errors.append(f"Missing required Fumadocs file: {file_path}")

        # Check next.config.mjs
        config = self.project_root / "apps/docs-fumadocs/next.config.mjs"
        if config.exists():
            content = config.read_text()
            
            # Check for theme mode configuration
            theme_mode = answers.get("docs_theme_mode", "auto")
            if theme_mode == "dark" and "dark" not in content:
                self.warnings.append("Dark theme mode not reflected in next.config.mjs")

    def _validate_docusaurus(self, answers: Dict) -> None:
        """Validate Docusaurus-specific configuration."""
        # Check for required files
        required_files = [
            "apps/docs-docusaurus/docusaurus.config.js",
            "apps/docs-docusaurus/docs/intro.md",
        ]
        
        for file_path in required_files:
            full_path = self.project_root / file_path
            if not full_path.exists():
                self.errors.append(f"Missing required Docusaurus file: {file_path}")

        # Check docusaurus.config.js
        config = self.project_root / "apps/docs-docusaurus/docusaurus.config.js"
        if config.exists():
            content = config.read_text()
            
            # Check for theme configuration
            if "themeConfig" not in content:
                self.errors.append("themeConfig not found in docusaurus.config.js")


def main():
    """Main entry point."""
    if len(sys.argv) > 1:
        project_root = Path(sys.argv[1])
    else:
        project_root = Path.cwd()

    if not project_root.exists():
        print(f"❌ Project root not found: {project_root}")
        sys.exit(1)

    validator = DocsConfigValidator(project_root)
    success = validator.validate()
    
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
