"""Tests for Node template contracts (docs + api-node)."""

# pylint: disable=redefined-outer-name,import-outside-toplevel,too-few-public-methods

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

pytest.importorskip("jinja2")

pytestmark = pytest.mark.unit

NAMED_MERMAID_EXPORT = "export { mermaidThemeByColorMode }"
SIDEBAR_JS_REQUIRE = "require('./docs/api-reference/sidebar.js')"
STATIC_EXPORT = "output: 'export' as const"
FORCE_STATIC = "export const dynamic = 'force-static'"
NO_REVALIDATE = "export const revalidate = false"


@pytest.fixture
def template_dir() -> Path:
    """Get the template directory."""
    return Path(__file__).parents[2] / "template"


@pytest.fixture
def node_files_dir(template_dir: Path) -> Path:
    """Get the Node template files directory."""
    return template_dir / "files" / "node"


def _read(path: Path) -> str:
    """Read a template file as UTF-8 text."""
    return path.read_text(encoding="utf-8")


def _render(template_path: Path, **context: object) -> str:
    from jinja2 import Environment, FileSystemLoader

    env = Environment(loader=FileSystemLoader(str(template_path.parent)))
    return env.get_template(template_path.name).render(**context)


def _jinja_hits(root: Path, needle: str) -> list[str]:
    hits: list[str] = []
    for path in root.rglob("*.jinja"):
        if needle in _read(path):
            hits.append(str(path.relative_to(root)))
    return hits


def _node_engine_major(spec: str) -> int:
    match = re.search(r">=\s*(\d+)", spec)
    assert match is not None, f"expected node engines >=N, got {spec!r}"
    return int(match.group(1))


class TestDocusaurusMermaidNamedExport:
    """Docusaurus mermaid token bag stays file-local (no named export)."""

    def test_docusaurus_config_exists(self, node_files_dir: Path) -> None:
        """docusaurus.config.ts.jinja should exist."""
        config = node_files_dir / "docs" / "docusaurus" / "docusaurus.config.ts.jinja"
        assert config.is_file()

    def test_mermaid_theme_bag_is_file_local(self, node_files_dir: Path) -> None:
        """mermaidThemeByColorMode is a file-local const, not a named export."""
        config = node_files_dir / "docs" / "docusaurus" / "docusaurus.config.ts.jinja"
        text = _read(config)
        assert "const mermaidThemeByColorMode =" in text
        assert NAMED_MERMAID_EXPORT not in text

    def test_named_mermaid_export_absent_from_docusaurus_templates(
        self, node_files_dir: Path
    ) -> None:
        """No docusaurus jinja file named-exports mermaidThemeByColorMode."""
        docusaurus_dir = node_files_dir / "docs" / "docusaurus"
        assert not _jinja_hits(docusaurus_dir, NAMED_MERMAID_EXPORT)

    def test_rendered_config_keeps_mermaid_bag_local(
        self, node_files_dir: Path
    ) -> None:
        """Rendered docusaurus config still has the bag and no named export."""
        config = node_files_dir / "docs" / "docusaurus" / "docusaurus.config.ts.jinja"
        rendered = _render(
            config,
            docs_module="enabled",
            docs_framework="docusaurus",
            docusaurus_mermaid="enabled",
            project_name="Test Project",
            project_slug="test-project",
        )
        assert "const mermaidThemeByColorMode =" in rendered
        assert NAMED_MERMAID_EXPORT not in rendered
        assert "export default config" in rendered


class TestDocusaurusSidebarJs:
    """OpenAPI sidebar.js require must stay deleted."""

    def test_sidebars_template_exists(self, node_files_dir: Path) -> None:
        """sidebars.ts.jinja should exist."""
        sidebars = node_files_dir / "docs" / "docusaurus" / "sidebars.ts.jinja"
        assert sidebars.is_file()

    def test_sidebar_js_require_absent_from_sidebars(
        self, node_files_dir: Path
    ) -> None:
        """sidebars.ts.jinja must not require the v4 sidebar.js path."""
        sidebars = node_files_dir / "docs" / "docusaurus" / "sidebars.ts.jinja"
        text = _read(sidebars)
        assert SIDEBAR_JS_REQUIRE not in text
        assert "dirName: 'api-reference'" in text

    def test_sidebar_js_require_absent_from_docusaurus_templates(
        self, node_files_dir: Path
    ) -> None:
        """No leftover sidebar.js require under docusaurus jinja."""
        docusaurus_dir = node_files_dir / "docs" / "docusaurus"
        assert not _jinja_hits(docusaurus_dir, SIDEBAR_JS_REQUIRE)

    def test_rendered_sidebars_omit_sidebar_js_require(
        self, node_files_dir: Path
    ) -> None:
        """Rendered sidebars keep the autogenerated api-reference category."""
        sidebars = node_files_dir / "docs" / "docusaurus" / "sidebars.ts.jinja"
        rendered = _render(
            sidebars,
            docs_module="enabled",
            docs_framework="docusaurus",
            docusaurus_openapi="enabled",
            api_module="enabled",
            api_languages=["node"],
            api_features=[],
            cli_module="disabled",
            graphql_api_module="disabled",
            websocket_module="disabled",
            mcp_module="disabled",
            project_name="Test Project",
            project_slug="test-project",
        )
        assert SIDEBAR_JS_REQUIRE not in rendered
        assert "dirName: 'api-reference'" in rendered


class TestFumadocsStaticExport:
    """Fumadocs static-export contracts (no middleware / rewrite path)."""

    def test_middleware_template_deleted(self, node_files_dir: Path) -> None:
        """fumadocs middleware.ts.jinja must not exist."""
        middleware = node_files_dir / "docs" / "fumadocs" / "middleware.ts.jinja"
        assert not middleware.exists()

    def test_next_config_output_export_as_const(self, node_files_dir: Path) -> None:
        """next.config.ts.jinja pins static export with `as const`."""
        next_config = node_files_dir / "docs" / "fumadocs" / "next.config.ts.jinja"
        text = _read(next_config)
        assert STATIC_EXPORT in text

    def test_rendered_next_config_output_export_as_const(
        self, node_files_dir: Path
    ) -> None:
        """Rendered Next config keeps `output: 'export' as const`."""
        next_config = node_files_dir / "docs" / "fumadocs" / "next.config.ts.jinja"
        rendered = _render(
            next_config,
            docs_module="enabled",
            docs_framework="fumadocs",
        )
        assert STATIC_EXPORT in rendered

    @pytest.mark.parametrize(
        "relative",
        [
            "docs/fumadocs/app/sitemap.ts.jinja",
            "docs/fumadocs/app/robots.ts.jinja",
        ],
    )
    def test_static_route_flags(self, node_files_dir: Path, relative: str) -> None:
        """sitemap and robots stay force-static with revalidate disabled."""
        text = _read(node_files_dir / relative)
        assert FORCE_STATIC in text
        assert NO_REVALIDATE in text

    @pytest.mark.parametrize(
        "relative",
        [
            "docs/fumadocs/app/sitemap.ts.jinja",
            "docs/fumadocs/app/robots.ts.jinja",
        ],
    )
    def test_rendered_static_route_flags(
        self, node_files_dir: Path, relative: str
    ) -> None:
        """Rendered sitemap and robots keep the static-export flags."""
        rendered = _render(
            node_files_dir / relative,
            docs_module="enabled",
            docs_framework="fumadocs",
            project_slug="test-project",
        )
        assert FORCE_STATIC in rendered
        assert NO_REVALIDATE in rendered

    def test_search_route_uses_requestless_static_get(
        self, node_files_dir: Path
    ) -> None:
        """Static export must not bind GET to a Request-reading handler."""
        text = _read(
            node_files_dir
            / "docs"
            / "fumadocs"
            / "app"
            / "api"
            / "search"
            / "route.ts.jinja"
        )
        assert "export const GET = search.staticGET" not in text
        assert "export async function GET()" in text
        assert "return staticGET()" in text


class TestApiNodePackage:
    """api-node package.json.jinja name, engines, and test/runtime deps."""

    def test_package_json_exists(self, node_files_dir: Path) -> None:
        """api-node package.json.jinja should exist."""
        package_json = node_files_dir / "apps" / "api-node" / "package.json.jinja"
        assert package_json.is_file()

    def test_package_json_name_engines_fastify_vitest(
        self, node_files_dir: Path
    ) -> None:
        """Rendered api-node package is named, node>=20, with fastify and vitest."""
        package_json = node_files_dir / "apps" / "api-node" / "package.json.jinja"
        rendered = _render(
            package_json,
            api_module="enabled",
            api_languages=["node"],
            project_name="Test Project",
        )
        data = json.loads(rendered)
        assert data["name"] == "api-node"
        node_engine = data["engines"]["node"]
        assert _node_engine_major(node_engine) >= 20
        assert "fastify" in data["dependencies"]
        assert "vitest" in data["devDependencies"]


class TestDocusaurusTailwindDeleted:
    """Docusaurus Tailwind v4 is CSS-first; the TS config must stay gone."""

    def test_tailwind_config_template_absent(self, node_files_dir: Path) -> None:
        """docs/docusaurus/tailwind.config.ts.jinja must not exist."""
        tailwind = node_files_dir / "docs" / "docusaurus" / "tailwind.config.ts.jinja"
        assert not tailwind.exists()
